version: "3.2"
services:
  frontend:
    build: ./frontend
    image: frontend
    ports:
      - 3000:80
    environment:
      # IP address of the server.
      # It must match exactly the IP of the server, indeed.
      REACT_APP_BACKEND_HOST: 'localhost' 
      REACT_APP_BACKEND_PORT: '3001'
    restart: always


  backend:
    build: ./backend
    image: backend
    ports:
      - 3001:3001
    environment:
      CONFIG_MYSQL_DATABASE: ratingdb
      CONFIG_MYSQL_USER: root
      CONFIG_MYSQL_PASSWORD: secret
      CONFIG_MYSQL_HOST: db1
      # from the backend, connect to MySQL via the "db" hostname on port 3306
      CONFIG_MYSQL_PORT: 3306
    depends_on:
      - db1
    restart: always
    
  db1:
    container_name: db1
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST_IP: db1
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ratingdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    restart: always


  adminer:
    image: adminer
    ports:
      - "8082:8080"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db1
    ports:
      - "3027:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: secret
      PMA_HOST: db1
      PMA_PORT: 3306
    restart: always
    
  flyway:
    image: flyway/flyway:7
    # We concatenate the command below to the ENTRYPOINT of the flyway Docker container:
    # The ENTRYPOINT is simply `flyway`
    command: ["-url=jdbc:mysql://db1:3306/ratingdb?verifyServerCertificate=false&useSSL=false", "-user=root", "-password=secret", "-connectRetries=100", "migrate"]
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db1
    restart: "no"

