# This workflow installs the dependencies, run the tests
# and builds the Android app.
# (unless some of the steps are commented out)
#

on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
name: Frontend
jobs:
  build:
    name: Run flutter test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        # flutter-version: '2.16.1'
        channel: 'stable'

    - name: Get dependencies
      run: flutter pub get

    - name: Flutter generate internationalization files
      run: flutter gen-l10n

    - name: Flutter build web
      run: flutter build web

    - name: Flutter analyze
      run: flutter analyze || true # If this fails, for now, we don't fail the whole action

    - name: Flutter test
      run: flutter test

# XXX We could Build and Release apk, but this would probably take a lot more time:
#   - run: flutter build apk --debug --split-per-abi
#   - name: Create a Release APK
#     uses: ncipollo/release-action@v1
#     with:
#       artifacts: "build/app/outputs/apk/debug/*.apk"
#       token: ${{ secrets.TOKEN }}

